name: CI (Dockerized)

on:
  push:
    branches: [ main ]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t sample-backend-test ./backend

      - name: Run tests inside Docker
        run: docker run --rm sample-backend-test npm test

